SiteTitle: My Blog
PageTitle: |
  =>
  {
    string siteTitle = Context.Settings.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
PostSources: posts/*